renovate:
  stage: dependencies
  image:
    name: renovate/renovate:latest
    entrypoint: [""]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  variables:
    RENOVATE_PLATFORM: gitlab
    RENOVATE_ENDPOINT: $CI_API_V4_URL
    RENOVATE_TOKEN: $RENOVATE_TOKEN
    RENOVATE_AUTODISCOVER: "false"
    RENOVATE_REPOSITORIES: $CI_PROJECT_PATH
  script:
    - renovate
